### ISSUE TITLE
Reset wiremock takes too long

### ISSUE THREAD

**Issue by gromanas** [rodolpheche/wiremock-docker#37]
Hello! 

We are using the latest docker image of wiremock, for testing a react web application.
We have noticed that when we use the `__admin/mappings/reset` or `__admin/reset` to reset wiremock the response of success takes almost 5 to 6 seconds. We have tried different endpoints to reset using `http://localhost:{port}` or `http://172.17.0.1:{port}`. We got in the container and we run a curl command to reset the wiremock `curl -X POST 'http://172.17.0.1:{port}/__admin/mappings/reset'` and again we count around 5 secs. In standalone wiremock we noticed that those actions take ms to complete.  The scale of our wiremock counts 283 mappings.

Have you seen such an issue before? 
Thank you in advance!

**Comment by rodolpheche** [comment]
Hello,

I tried to reproduce with a set of 10000 simple mappings with json files and it takes less that 1 second to call reset api endpoint.
Could you give me a link to your wiremock files to allow me to investigate on this behaviour ?

**Comment by gromanas** [comment]
Thank you for your time! 

I think we found what caused this delay. We start wiremock using `docker-compose`. So we mount our local volumes with the `__files` and `mappings` folder.

```
webmock:
    image: rodolpheche/wiremock
    container_name: wiremock
    ports:
      - "1993:8080"
    volumes:
      - ./tests/wiremock/mocks:/home/wiremock
    command: ["--verbose", "--local-response-templating"]
```

The solution that we found and `__admin/reset` time came back to normal (ms) is that we create our own `Dockerfile` so we can copy inside the container our mocks
